### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined 

### ISSUE THREAD

**Issue by 4nx** [papermerge/papermerge.js#18]
Hi there,

I wanted to test papermerge via docker compose or better said Portainer. Papermerge is up and running, I can login and the websocket connection seems to work as well. When I now tried to e.g.create a new folder I'll get the following error in the browser console:

```
Uncaught TypeError: Cannot set properties of undefined (setting 'title')
    at a.onSubmit (papermerge-096a5e9669979e53a4107446fd672eab.js:241:283)
    at a.handleKeyboardEvent (vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:5641:1280)
    at r (vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:5664:3)
    at e.handleKeyEventWithPropagation (vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:5673:10)
    at vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:5650:208
    at U._run (vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:3229:94)
    at U.run (vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:3192:13)
    at e.run (vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:1908:66)
    at l._respond (vendor-fe16d39c99c858dfbe7954f7b52e67f7.js:5650:119)
```

The "Create Folder" window stays open and nothing else works. I tried to use different browsers and different OS, but the problem seems to be within the instance.

The following compose file was used:

```
version: '3.7'
# Any top-level key starting with x- in a Docker Compose file will be
# ignored
x-backend: &backend  # yaml anchor definition
  image: ${APP_IMAGE}:${APP_TAG}
  volumes:
    - media_root:/app/media
  environment:
    # PAPERMERGE__<section>__<variable>
    - PAPERMERGE__MAIN__SECRET_KEY=${SECRET_KEY}
    - PAPERMERGE__DATABASE__TYPE=postgres
    - PAPERMERGE__DATABASE__USER=${DB_USER}
    - PAPERMERGE__DATABASE__NAME=${DB_NAME}
    - PAPERMERGE__DATABASE__PASSWORD=${DB_PASSWORD}
    - PAPERMERGE__DATABASE__HOST=${DB_HOST}
    - PAPERMERGE__REDIS__HOST=${REDIS_HOST}
    - PAPERMERGE__REDIS__PORT=${REDIS_PORT}
    - PAPERMERGE__ELASTICSEARCH__HOSTS=${ES_HOSTS}
    - PAPERMERGE__ELASTICSEARCH__PORT=${ES_PORT}
    - PAPERMERGE__MAIN__TIMEZONE=${TIMEZONE}
    - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
    - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    - DJANGO_SETTINGS_MODULE=config.settings
services:
  worker: # celery worker
    <<: *backend
    command: worker
  ws_server:  # websockets server / daphne
    <<: *backend
    command: ws_server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ws_server.rule=Host(`${USE_HOSTNAME}`) && PathPrefix(`/ws/`)"
  backend:  # rest api backend / uwsgi
    <<: *backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${USE_HOSTNAME}`) && PathPrefix(`/api/`)"
  db:
    image: postgres:14.4
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
  traefik:
    image: "traefik:v2.6"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  frontend: # emberjs
    image: ${PAPERMERGE_JS_IMAGE}:${PAPERMERGE_JS_TAG}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${USE_HOSTNAME}`) && PathPrefix(`/`)"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  postgres_data:
  media_root:
  redisdata:
```

And those env values:

```
APP_IMAGE=ghcr.io/papermerge/papermerge
APP_TAG=latest
PAPERMERGE_JS_IMAGE=ghcr.io/papermerge/papermerge.js
PAPERMERGE_JS_TAG=latest
DB_USER=postgres
DB_NAME=postgres
DB_PASSWORD=postgres
DB_HOST=db
DB_PORT=5433
USE_HOSTNAME=papermerge.home.arpa
REDIS_HOST=redis
REDIS_PORT=6380
ES_HOSTS=es
ES_PORT=9200
SECRET_KEY=ooSh3OhCh6doo4iegh6Nai8seey2cei7pietob8AGaede5iev9zie8Ahheeghu2d
SUPERUSER_USERNAME=admin
SUPERUSER_EMAIL=xxx
SUPERUSER_PASSWORD=admin
```

Every container seems to run:
```
7597e0950934   ghcr.io/papermerge/papermerge:latest                   "/run.bash worker"       14 minutes ago   Up 14 minutes           8000/tcp                                                                                                                          papermerge_worker_1
071795f28274   traefik:v2.6                                           "/entrypoint.sh --ap…"   14 minutes ago   Up 14 minutes           0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                                      papermerge_traefik_1
208c66ee80cd   docker.elastic.co/elasticsearch/elasticsearch:7.16.2   "/bin/tini -- /usr/l…"   14 minutes ago   Up 14 minutes           0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 0.0.0.0:9300->9300/tcp, :::9300->9300/tcp                                              papermerge_es_1
04531f7ce830   postgres:14.4                                          "docker-entrypoint.s…"   14 minutes ago   Up 14 minutes           0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                         papermerge_db_1
57bb00586082   redis:6                                                "docker-entrypoint.s…"   14 minutes ago   Up 14 minutes           0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                                                         papermerge_redis_1
207078fc38e3   ghcr.io/papermerge/papermerge:latest                   "/run.bash ws_server"    14 minutes ago   Up 14 minutes           8000/tcp                                                                                                                          papermerge_ws_server_1
bb15148b950e   ghcr.io/papermerge/papermerge.js:latest                "nginx -g 'daemon of…"   14 minutes ago   Up 14 minutes           80/tcp                                                                                                                            papermerge_frontend_1
a24f7ed3d635   ghcr.io/papermerge/papermerge:latest                   "/run.bash server"       14 minutes ago   Up 14 minutes           8000/tcp                                                                                                                          papermerge_backend_1
```
